/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author AK
 */
public class Calculator extends javax.swing.JFrame {

    double Number1;
    double Number2;
    double Result;
    String op;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtRESULT = new javax.swing.JTextField();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnSUB = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnMUL = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDOT = new javax.swing.JButton();
        jbtnEQUAL = new javax.swing.JButton();
        jbtn1DIV = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnCE = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnADD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULATOR");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 230, 20));

        jtxtRESULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRESULTActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtRESULT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 50));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, 60));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, 60));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, 60));

        jbtnSUB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnSUB.setText("-");
        jbtnSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSUBActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 60, 60));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 60, 60));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 60, 60));

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 60, 60));

        jbtnMUL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnMUL.setText("*");
        jbtnMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMULActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 60, 60));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 60, 60));

        jbtnDOT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDOT.setText(".");
        jbtnDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDOTActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 60, 60));

        jbtnEQUAL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnEQUAL.setText("=");
        jbtnEQUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEQUALActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEQUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 60, 60));

        jbtn1DIV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtn1DIV.setText("/");
        jbtn1DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1DIVActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn1DIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 60, 60));

        jbtnBS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnBS.setText("BS");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 60));

        jbtnCE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, 60));

        jButtonC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, 60));

        jbtnPM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnPM.setText("+/-");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, 60));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, 60));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, 60));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 60, 60));

        jbtnADD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnADD.setText("+");
        jbtnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnADDActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumber(String q){
        String Nums=jtxtRESULT.getText()+q;
        jtxtRESULT.setText(Nums);
    }
        
    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        EnterNumber("5");
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        EnterNumber("8");
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtnDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDOTActionPerformed
        if(!jtxtRESULT.getText().contains("."))
        {
            jtxtRESULT.setText(jtxtRESULT.getText()+jbtnDOT.getText());
        }
    }//GEN-LAST:event_jbtnDOTActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtRESULT.setText("");
        String Fn,Ln;
        Fn=String.valueOf(Number1);
        Ln=String.valueOf(Number2);
        Fn="";
        Ln="";
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        EnterNumber("2");
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jtxtRESULT.setText("");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        EnterNumber("1");
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        EnterNumber("3");
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        EnterNumber("4");
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        EnterNumber("6");
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        EnterNumber("7");
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        EnterNumber("9");
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        EnterNumber("0");
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnEQUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEQUALActionPerformed
        Number2=Double.parseDouble(jtxtRESULT.getText());
        
        if(op=="+")
        {
            Result=Number1+Number2;
            jtxtRESULT.setText(String.valueOf(Result));
        }
        
        else if(op=="-")
        {
            Result=Number1-Number2;
            jtxtRESULT.setText(String.valueOf(Result));
        }
        
        else if(op=="*")
        {
            Result=Number1*Number2;
            jtxtRESULT.setText(String.valueOf(Result));
        }
        
        else if(op=="/")
        {
            Result=Number1/Number2;
            jtxtRESULT.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jbtnEQUALActionPerformed

    private void jbtnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnADDActionPerformed
        Number1=Double.parseDouble(jtxtRESULT.getText());
        jtxtRESULT.setText("");
        op="+";
    }//GEN-LAST:event_jbtnADDActionPerformed

    private void jbtnSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSUBActionPerformed
        Number1=Double.parseDouble(jtxtRESULT.getText());
        jtxtRESULT.setText("");
        op="-";
    }//GEN-LAST:event_jbtnSUBActionPerformed

    private void jbtnMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMULActionPerformed
        Number1=Double.parseDouble(jtxtRESULT.getText());
        jtxtRESULT.setText("");
        op="*";
    }//GEN-LAST:event_jbtnMULActionPerformed

    private void jbtn1DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1DIVActionPerformed
        Number1=Double.parseDouble(jtxtRESULT.getText());
        jtxtRESULT.setText("");
        op="/";
    }//GEN-LAST:event_jbtn1DIVActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        String backspace=null;
        if(jtxtRESULT.getText().length()>0)
        {
            StringBuilder sb=new StringBuilder(jtxtRESULT.getText());
            sb.deleteCharAt(jtxtRESULT.getText().length()-1);
            backspace=sb.toString();
            jtxtRESULT.setText(backspace);
        }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        double nums=Double.parseDouble(String.valueOf(jtxtRESULT.getText()));
        nums=nums*(-1);
        jtxtRESULT.setText(String.valueOf(nums));
        
    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jtxtRESULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRESULTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRESULTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn1DIV;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnADD;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDOT;
    private javax.swing.JButton jbtnEQUAL;
    private javax.swing.JButton jbtnMUL;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnSUB;
    private javax.swing.JTextField jtxtRESULT;
    // End of variables declaration//GEN-END:variables
}
